---
kind: Service
apiVersion: v1
metadata:
  name: heketi-bootstrap
  labels:
    app: heketi-bootstrap
spec:
  type: LoadBalancer
  selector:
    app: heketi-bootstrap
  ports:
  - name: deploy-heketi
    port: 8080
    targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: heketi-bootstrap
  labels:
    app: heketi-bootstrap
spec:
  replicas: 1
  template:
    metadata:
      name: heketi-bootstrap
      labels:
        app: heketi-bootstrap
    spec:
      serviceAccount: heketi-bootstrapper
      containers:
      - name: heketi
        image: heketi/heketi:7
        command:
          - heketi
          - --config=/etc/heketi/heketi.json
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: db
          mountPath: "/var/lib/heketi"
        - name: config
          mountPath: /etc/heketi
        readinessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 3
          httpGet:
            path: "/hello"
            port: 8080
        livenessProbe:
          timeoutSeconds: 3
          initialDelaySeconds: 30
          httpGet:
            path: "/hello"
            port: 8080
      volumes:
      - name: db
      - name: config
        secret:
          secretName: heketi-mgmt