apiVersion: v1
kind: ServiceAccount
metadata:
  name: heketi-bootstrapper
  namespace: storage
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heketi-bootstrapper
  namespace: storage
rules:
- apiGroups: ["*"] # "" indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heketi-bootstrapper
  namespace: storage
subjects:
- kind: ServiceAccount
  name: heketi-bootstrapper
  namespace: storage
roleRef:
  kind: Role
  name: heketi-bootstrapper
  apiGroup: rbac.authorization.k8s.io