apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: heketi
  name: heketi
spec:
  endpoints:
  - interval: 10s
    port: heketi
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - storage
  selector:
    matchLabels:
      app: heketi
